#!/bin/bash

github_user="splishie"
config_directory="usap-a2"

# Install binaries - neccessary for kernal install
sudo apt install raspberrypi-kernel-headers build-essential bc git wget bison flex libssl-dev make

# Clone repository containing linux kernel for rasberry pi
git clone --depth=1 https://github.com/raspberrypi/linux

# Clone repository that contains config file
git clone --depth=1 https://github.com/$github_user/$config_directory.git


# Copy the config file into the downloaded linux repository
echo "Copying config file"
cp .config linux/

#Start Performance monitoring
sh usap-a2/performance_monitor & monitor_pid=$!

#Making Backup
echo "Creating Backup"
mkdir ~/kernel_backup
mkdir ~/kernel_backup/overlays
cp /boot/*.dtb ~/kernel_backup
cp /boot/overlays/*.dtb ~/kernel_backup/overlays
cp /boot/overlays/*.dtb* ~/kernel_backup/overlays
cp /boot/overlays/README ~/kernel_backup/overlays

tar -zcvf ~/old_kernel.tar.gz ~/kernel_backup

# Make the kernal
echo "Beggining make proccess"
cd linux
KERNEL=kernel71

make -j4 zImage modules dtbs

# Install the final modules
echo "Installing modules"
sudo make modules_install

# Copy the required files to the final destination
echo "Copying required files to the final destination"
sudo cp arch/arm/boot/dts/*.dtb /boot/
sudo cp arch/arm/boot/dts/overlays/*.dtb* /boot/overlays/
sudo cp arch/arm/boot/dts/overlays/README /boot/overlays/
sudo cp arch/arm/boot/zImage /boot/$KERNEL.img

#Send USR1 signal to end monitoring process
kill -s USR1 $monitor_pid >/dev/null

#Reboot the system for the changes to take place
sudo reboot

