#!/bin/bash
#USAP Performance Monitoring Script

#Path for Executables
VCGENCMD=/usr/bin/vcgencmd

#Listen for USR1 signal to stop the process
trap "kill $$" USR1

#Performance monitoring

#Adding headings
printf "%s\t%s\t%s\n" "TIME(s)" "TEMP(C)" "Clock(Hz)"> kernel_performance_data

time=0

#Monitor Temperature every 1 second
while true
do
	temp=$(vcgencmd measure_temp | egrep -o '[0-9]*\.[0-9]*')
	clock=$(vcgencmd measure_clock arm | grep '=[0-9]*' | cut -d '=' -f 2-)
	printf "%s\t%s\t%s\n" "$time" "$temp" "$clock" >> kernel_performance_data
	sleep 1
	time=$(($time+1))
done
